version: '3'
services:
  auth-service:
    build: ./services/auth-service
    ports:
      - '3001:3001'
    depends_on:
      - mongo
  
  project-service:
    build: ./services/project-service
    ports:
      - '3002:3002'
    depends_on:
      - mongo

  task-service:
    build: ./services/task-service
    ports:
      - '3003:3003'
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - '27017:27017'
